# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=160)),
                ('iletisim_nedeni', models.CharField(max_length=60)),
                ('mail', models.EmailField(max_length=254)),
                ('aciklama', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'db_table': 'Contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lang_code', models.CharField(max_length=100, unique=True, verbose_name='Vurgulama')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('mime', models.CharField(help_text='Snippeti dosya olarak gönderirken kullanılacak MIME.', max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('highlighted', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=160)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('publish', models.DateTimeField()),
                ('lexer', models.CharField(default='_code', max_length=60)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('expire_type', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('auth_code', models.CharField(db_index=True, max_length=32)),
                ('view_count', models.IntegerField(default=0)),
                ('ip_adress', models.GenericIPAddressField()),
                ('is_public', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Paste',
                'verbose_name_plural': 'Yapıştırılanlar',
                'db_table': 'Paste',
                'ordering': ('-view_count',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paste.Paste')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PasteUser',
                'db_table': 'PasteUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugs_id', models.SlugField()),
                ('mail', models.EmailField(max_length=254)),
                ('reason', models.CharField(default='spammer', max_length=255)),
                ('rapor_nedeni', models.TextField()),
            ],
            options={
                'verbose_name': 'Report',
                'db_table': 'Report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TagLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paste.Paste')),
            ],
            options={
                'verbose_name': 'TagLists',
                'db_table': 'TagLists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tags',
                'db_table': 'Tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'db_table': 'Visitor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='taglists',
            name='tagid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paste.Tags'),
        ),
    ]
